Added case 2 questions to the server room
ConorMFinn/CO600-SeriousCyberSec pull request #109
Opened 2021-01-28 16:14 UTC by Alice-Jaffray

**Description of work.**

Added questions to the server room for case 2

**To test:**

Open the server room and check the question objects

Fixes #105

2021-01-28 18:53 UTC, ConorMFinn commented
This branch needs to have it's conflicts resolved before review

2021-01-28 22:26 UTC, ConorMFinn commented
I am getting this error when attempting to open the `ServerRoom` scene: 
`The file 'Assets/Rooms/ServerRoom.unity' seems to have merge conflicts. Please open it in a text editor and fix the merge.`

It may need rebasing instead of this merge commit?

2021-02-01 10:18 UTC, ConorMFinn requested changes
Questions look good and I like the new assets. Just a few notes:
- The canvases should be scaled using the "Anchor Presets" (click the square to the left of the `PosX` and `Width` boxes; Hold `alt` and `Shift` and click the bottom right object to stretch the canvas to the full area) and the Scale needs resetting to 1 for all values
- The buttons need assigning their `OnClick` methods. (Click the button, scroll down to the `OnClick()` section. Drag the object in the scene that is interacted with onto the Object section. Then function is then `ObjectInteraction > Correct()` for the right answer and `ObjectIneraction > Incorrect(Button)` for the wrong ones. The button you're assigning is then dragged onto the parameter

2021-02-05 13:17 UTC, ConorMFinn requested changes
Questions and new assets look good. Only note is that `ServerQuestion (2)` is too small and needs to be stretched like the rest. 

I also want to check if it should be possible to press 'E' to interact with the objects, as that is not currently working if the scene is played?

2021-02-06 15:12 UTC, ConorMFinn requested changes
Nearly perfect! Just a couple of little things:
- The level 2 main menu button needs to have `Interactable` ticked
- The `serverTower` in the top left seems to have been assigned the wrong question canvas

2021-02-06 15:12 UTC, cailafinn commented on project/sherLOCKED/Assets/Scripts/Menus/MainMenuController.cs
> +        ScoreManager.Instance.Reset();
Needs to include a call to the level manager to set the current level (see above `level1()` method)

2021-02-06 17:54 UTC, Alice-Jaffray commented on project/sherLOCKED/Assets/Scripts/Menus/MainMenuController.cs
> +        ScoreManager.Instance.Reset();
I don't see what you mean

2021-02-06 17:55 UTC, Alice-Jaffray commented on project/sherLOCKED/Assets/Scripts/Menus/MainMenuController.cs
> +        ScoreManager.Instance.Reset();
I don't see what you mean

2021-02-08 11:35 UTC, ConorMFinn approved these changes
Looks good! Thanks for pushing this through :)

2021-02-08 11:35 UTC, merged