Created conservatory
ConorMFinn/CO600-SeriousCyberSec pull request #160
Opened 2021-02-17 18:52 UTC by Alice-Jaffray

**Description of work.**

Create  conservatory room ( + assets needed)
Add new room between library & dining room for level 4
Closed door to the conservatory in level 1 & 3
Server room door moved to bottom in level 2 

**To test:**

check it out! FYI the minimap will go in with the minimap ticket 

Fixes #151

2021-02-17 19:17 UTC, ConorMFinn requested changes
Looks good, just a few notes:
- Objects need to be on the Character sorting layer or Sherry will appear in front of them
- There is no hitbox for the edge of the room, so you can just walk out the top, bottom, or sides 
- The question in the conservatory already exists in the server room, attached to the desk. I would also prefer if we used a different question in the conservatory as the password one I think makes sense being attached to the server room PC

2021-02-17 21:00 UTC, Alice-Jaffray commented
Lol completely forgot to put an edge collider and delete the question from the server room

2021-02-17 23:15 UTC, ConorMFinn requested changes
The desk still has the interactable tag and the object interaction script on it. 

I would also prefer if the password question stayed on the desk object and one of the other questions was moved to the conservatory that doesn't have a good relation to the object it's attached to

2021-02-18 12:05 UTC, ConorMFinn requested changes
Almost perfect, but the question in the conservatry has the incorrect "wrong answer" text on it. just needs changing to the one from the hall flower pot question

2021-02-18 18:05 UTC, ConorMFinn commented on project/sherLOCKED/Assets/Rooms/Level4/Conservatory.unity
> +    Whoops. It''s about making security as easy as possible for the user. '
This appears twice when you get the question wrong.

2021-02-18 18:05 UTC, ConorMFinn requested changes

2021-02-18 18:05 UTC, ConorMFinn commented on project/sherLOCKED/Assets/Rooms/Level4/Conservatory.unity
> +    Whoops. It''s about making security as easy as possible for the user. '
This appears twice if you get the question wrong.

2021-02-18 19:06 UTC, ConorMFinn approved these changes

2021-02-18 19:06 UTC, merged