Allow object interaction
ConorMFinn/CO600-SeriousCyberSec pull request #42
Opened 2020-12-09 23:01 UTC by Alice-Jaffray

**Description of work.**

When Sherry is in the perimeter of the desk, the text appears on the left of the scene prompting the player to press E or Space to interact with the desk. When one of these buttons is pressed, the text changes to show the player that the desk has been interacted with.

**To test:**

Start the game, approach the desk, check that the text is correct.

Fixes #37

2020-12-10 12:49 UTC, ConorMFinn requested changes
Some brief code comments and some functional stuff:
- Sherry appears behind the desk, may be worth creating a sorting layer for characters that appears above other things. 
- Sherry is currently on the grid lines. Setting their x position to `0.5` would put them in the right place.

2020-12-10 12:49 UTC, ConorMFinn commented on project/sherLOCKED/Assets/Scripts/Sherry/SherryInteract.cs
> +    void OnTriggerEnter2D(Collider2D other)
Could we have comments on these methods, please?

2020-12-10 12:49 UTC, ConorMFinn commented on project/sherLOCKED/Assets/Scripts/Sherry/SherryInteract.cs
> +            inCollider = !inCollider;
Is there a reason this is swapping, rather than explicit setting to `true`? The former seems less clear to me

2020-12-11 11:31 UTC, ConorMFinn requested changes
Nearly perfect, just one more thing:
Object interaction should really only occur within the range of the computer
Setting offset to (0.5, 0) and size to (0.5, 1) seems to work well for this

2020-12-11 15:40 UTC, Alice-Jaffray commented
I thought the object to interact with was the desk but as it's the computer I'll change it 👍

2020-12-11 17:35 UTC, ConorMFinn approved these changes
Looks good to me, nice work! 👍

2020-12-11 17:35 UTC, merged